name: 'poznan_it_market'
version: '0.1.0'
profile: 'poznan_it_market'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  poznan_it_market:
    +materialized: view

snapshots:
  poznan_it_market:
    +enabled: false
